// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Engine defines the supported search engines.
type Engine int32

const (
	Engine_ENGINE_UNSPECIFIED Engine = 0
	Engine_ENGINE_GOOGLE      Engine = 1
	Engine_ENGINE_BING        Engine = 2
	Engine_ENGINE_BRAVE       Engine = 3
	Engine_ENGINE_DUCKDUCKGO  Engine = 4
)

// Enum value maps for Engine.
var (
	Engine_name = map[int32]string{
		0: "ENGINE_UNSPECIFIED",
		1: "ENGINE_GOOGLE",
		2: "ENGINE_BING",
		3: "ENGINE_BRAVE",
		4: "ENGINE_DUCKDUCKGO",
	}
	Engine_value = map[string]int32{
		"ENGINE_UNSPECIFIED": 0,
		"ENGINE_GOOGLE":      1,
		"ENGINE_BING":        2,
		"ENGINE_BRAVE":       3,
		"ENGINE_DUCKDUCKGO":  4,
	}
)

func (x Engine) Enum() *Engine {
	p := new(Engine)
	*p = x
	return p
}

func (x Engine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Engine) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[0].Descriptor()
}

func (Engine) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[0]
}

func (x Engine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Engine.Descriptor instead.
func (Engine) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

// ErrorCode defines standardized OSP error codes.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_SUCCESS           ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_QUERY     ErrorCode = 1
	ErrorCode_ERROR_CODE_WORKER_TIMEOUT    ErrorCode = 2
	ErrorCode_ERROR_CODE_WORKER_DISCONNECT ErrorCode = 3
	ErrorCode_ERROR_CODE_RATE_LIMITED      ErrorCode = 4
	ErrorCode_ERROR_CODE_CAPTCHA_DETECTED  ErrorCode = 5
	ErrorCode_ERROR_CODE_PROVIDER_DOWN     ErrorCode = 6
	ErrorCode_ERROR_CODE_INTERNAL_ERROR    ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_SUCCESS",
		1: "ERROR_CODE_INVALID_QUERY",
		2: "ERROR_CODE_WORKER_TIMEOUT",
		3: "ERROR_CODE_WORKER_DISCONNECT",
		4: "ERROR_CODE_RATE_LIMITED",
		5: "ERROR_CODE_CAPTCHA_DETECTED",
		6: "ERROR_CODE_PROVIDER_DOWN",
		7: "ERROR_CODE_INTERNAL_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_SUCCESS":           0,
		"ERROR_CODE_INVALID_QUERY":     1,
		"ERROR_CODE_WORKER_TIMEOUT":    2,
		"ERROR_CODE_WORKER_DISCONNECT": 3,
		"ERROR_CODE_RATE_LIMITED":      4,
		"ERROR_CODE_CAPTCHA_DETECTED":  5,
		"ERROR_CODE_PROVIDER_DOWN":     6,
		"ERROR_CODE_INTERNAL_ERROR":    7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

// SearchRequest defines the parameters for a search task.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Engine        Engine                 `protobuf:"varint,3,opt,name=engine,proto3,enum=protocol.Engine" json:"engine,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_UNSPECIFIED
}

func (x *SearchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SearchRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

// ResultItem matches the Brave Search API result schema.
type ResultItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Title       string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url         string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Age         string                 `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	Language    string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Extra       map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// OSP Metadata (Internal)
	SourceEngine  Engine `protobuf:"varint,7,opt,name=source_engine,json=sourceEngine,proto3,enum=protocol.Engine" json:"source_engine,omitempty"`
	WorkerId      string `protobuf:"bytes,8,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerRegion  string `protobuf:"bytes,9,opt,name=worker_region,json=workerRegion,proto3" json:"worker_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultItem) Reset() {
	*x = ResultItem{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultItem) ProtoMessage() {}

func (x *ResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultItem.ProtoReflect.Descriptor instead.
func (*ResultItem) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *ResultItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResultItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ResultItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResultItem) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *ResultItem) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ResultItem) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *ResultItem) GetSourceEngine() Engine {
	if x != nil {
		return x.SourceEngine
	}
	return Engine_ENGINE_UNSPECIFIED
}

func (x *ResultItem) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ResultItem) GetWorkerRegion() string {
	if x != nil {
		return x.WorkerRegion
	}
	return ""
}

// SearchResponse defines the results returned by a worker.
type SearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Results         []*ResultItem          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	ScrapeLatencyMs uint32                 `protobuf:"varint,3,opt,name=scrape_latency_ms,json=scrapeLatencyMs,proto3" json:"scrape_latency_ms,omitempty"`
	ErrorCode       ErrorCode              `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=protocol.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	WorkerId        string                 `protobuf:"bytes,6,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerRegion    string                 `protobuf:"bytes,7,opt,name=worker_region,json=workerRegion,proto3" json:"worker_region,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SearchResponse) GetResults() []*ResultItem {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetScrapeLatencyMs() uint32 {
	if x != nil {
		return x.ScrapeLatencyMs
	}
	return 0
}

func (x *SearchResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *SearchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SearchResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SearchResponse) GetWorkerRegion() string {
	if x != nil {
		return x.WorkerRegion
	}
	return ""
}

// RegisterRequest is sent by a worker to join the cluster.
type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedEngines []Engine               `protobuf:"varint,3,rep,packed,name=supported_engines,json=supportedEngines,proto3,enum=protocol.Engine" json:"supported_engines,omitempty"`
	PublicKey        string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Region           string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"` // e.g., US-East, ID-Jakarta
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetSupportedEngines() []Engine {
	if x != nil {
		return x.SupportedEngines
	}
	return nil
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// RegisterResponse is sent by the master after registration.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WorkerStatus is sent by the worker to report health and task results.
type WorkerStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkerId    string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsage    float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage float32                `protobuf:"fixed32,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveTasks uint32                 `protobuf:"varint,4,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	// If the worker just finished a task, it includes the result here.
	CompletedTask *SearchResponse `protobuf:"bytes,5,opt,name=completed_task,json=completedTask,proto3" json:"completed_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatus) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *WorkerStatus) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *WorkerStatus) GetActiveTasks() uint32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *WorkerStatus) GetCompletedTask() *SearchResponse {
	if x != nil {
		return x.CompletedTask
	}
	return nil
}

// MasterCommand is sent by the master to assign tasks or control the worker.
type MasterCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*MasterCommand_Task
	//	*MasterCommand_Ping
	//	*MasterCommand_DisconnectReason
	Command       isMasterCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterCommand) Reset() {
	*x = MasterCommand{}
	mi := &file_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterCommand) ProtoMessage() {}

func (x *MasterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterCommand.ProtoReflect.Descriptor instead.
func (*MasterCommand) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{6}
}

func (x *MasterCommand) GetCommand() isMasterCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MasterCommand) GetTask() *SearchRequest {
	if x != nil {
		if x, ok := x.Command.(*MasterCommand_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *MasterCommand) GetPing() bool {
	if x != nil {
		if x, ok := x.Command.(*MasterCommand_Ping); ok {
			return x.Ping
		}
	}
	return false
}

func (x *MasterCommand) GetDisconnectReason() string {
	if x != nil {
		if x, ok := x.Command.(*MasterCommand_DisconnectReason); ok {
			return x.DisconnectReason
		}
	}
	return ""
}

type isMasterCommand_Command interface {
	isMasterCommand_Command()
}

type MasterCommand_Task struct {
	Task *SearchRequest `protobuf:"bytes,1,opt,name=task,proto3,oneof"`
}

type MasterCommand_Ping struct {
	Ping bool `protobuf:"varint,2,opt,name=ping,proto3,oneof"`
}

type MasterCommand_DisconnectReason struct {
	DisconnectReason string `protobuf:"bytes,3,opt,name=disconnect_reason,json=disconnectReason,proto3,oneof"`
}

func (*MasterCommand_Task) isMasterCommand_Command() {}

func (*MasterCommand_Ping) isMasterCommand_Command() {}

func (*MasterCommand_DisconnectReason) isMasterCommand_Command() {}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x02\n" +
	"\rSearchRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12(\n" +
	"\x06engine\x18\x03 \x01(\x0e2\x10.protocol.EngineR\x06engine\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12;\n" +
	"\x06params\x18\x06 \x03(\v2#.protocol.SearchRequest.ParamsEntryR\x06params\x126\n" +
	"\bdeadline\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x02\n" +
	"\n" +
	"ResultItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03age\x18\x04 \x01(\tR\x03age\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x125\n" +
	"\x05extra\x18\x06 \x03(\v2\x1f.protocol.ResultItem.ExtraEntryR\x05extra\x125\n" +
	"\rsource_engine\x18\a \x01(\x0e2\x10.protocol.EngineR\fsourceEngine\x12\x1b\n" +
	"\tworker_id\x18\b \x01(\tR\bworkerId\x12#\n" +
	"\rworker_region\x18\t \x01(\tR\fworkerRegion\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\x0eSearchResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12.\n" +
	"\aresults\x18\x02 \x03(\v2\x14.protocol.ResultItemR\aresults\x12*\n" +
	"\x11scrape_latency_ms\x18\x03 \x01(\rR\x0fscrapeLatencyMs\x122\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x13.protocol.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tworker_id\x18\x06 \x01(\tR\bworkerId\x12#\n" +
	"\rworker_region\x18\a \x01(\tR\fworkerRegion\"\xbe\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\x11supported_engines\x18\x03 \x03(\x0e2\x10.protocol.EngineR\x10supportedEngines\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcf\x01\n" +
	"\fWorkerStatus\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x02R\vmemoryUsage\x12!\n" +
	"\factive_tasks\x18\x04 \x01(\rR\vactiveTasks\x12?\n" +
	"\x0ecompleted_task\x18\x05 \x01(\v2\x18.protocol.SearchResponseR\rcompletedTask\"\x8e\x01\n" +
	"\rMasterCommand\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x17.protocol.SearchRequestH\x00R\x04task\x12\x14\n" +
	"\x04ping\x18\x02 \x01(\bH\x00R\x04ping\x12-\n" +
	"\x11disconnect_reason\x18\x03 \x01(\tH\x00R\x10disconnectReasonB\t\n" +
	"\acommand*m\n" +
	"\x06Engine\x12\x16\n" +
	"\x12ENGINE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rENGINE_GOOGLE\x10\x01\x12\x0f\n" +
	"\vENGINE_BING\x10\x02\x12\x10\n" +
	"\fENGINE_BRAVE\x10\x03\x12\x15\n" +
	"\x11ENGINE_DUCKDUCKGO\x10\x04*\xfd\x01\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_SUCCESS\x10\x00\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_QUERY\x10\x01\x12\x1d\n" +
	"\x19ERROR_CODE_WORKER_TIMEOUT\x10\x02\x12 \n" +
	"\x1cERROR_CODE_WORKER_DISCONNECT\x10\x03\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\x04\x12\x1f\n" +
	"\x1bERROR_CODE_CAPTCHA_DETECTED\x10\x05\x12\x1c\n" +
	"\x18ERROR_CODE_PROVIDER_DOWN\x10\x06\x12\x1d\n" +
	"\x19ERROR_CODE_INTERNAL_ERROR\x10\a2\x92\x01\n" +
	"\rSearchService\x12A\n" +
	"\bRegister\x12\x19.protocol.RegisterRequest\x1a\x1a.protocol.RegisterResponse\x12>\n" +
	"\aConnect\x12\x16.protocol.WorkerStatus\x1a\x17.protocol.MasterCommand(\x010\x01B-Z+github.com/zulfikawr/go-search/pkg/protocolb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_search_proto_goTypes = []any{
	(Engine)(0),                   // 0: protocol.Engine
	(ErrorCode)(0),                // 1: protocol.ErrorCode
	(*SearchRequest)(nil),         // 2: protocol.SearchRequest
	(*ResultItem)(nil),            // 3: protocol.ResultItem
	(*SearchResponse)(nil),        // 4: protocol.SearchResponse
	(*RegisterRequest)(nil),       // 5: protocol.RegisterRequest
	(*RegisterResponse)(nil),      // 6: protocol.RegisterResponse
	(*WorkerStatus)(nil),          // 7: protocol.WorkerStatus
	(*MasterCommand)(nil),         // 8: protocol.MasterCommand
	nil,                           // 9: protocol.SearchRequest.ParamsEntry
	nil,                           // 10: protocol.ResultItem.ExtraEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_search_proto_depIdxs = []int32{
	0,  // 0: protocol.SearchRequest.engine:type_name -> protocol.Engine
	9,  // 1: protocol.SearchRequest.params:type_name -> protocol.SearchRequest.ParamsEntry
	11, // 2: protocol.SearchRequest.deadline:type_name -> google.protobuf.Timestamp
	10, // 3: protocol.ResultItem.extra:type_name -> protocol.ResultItem.ExtraEntry
	0,  // 4: protocol.ResultItem.source_engine:type_name -> protocol.Engine
	3,  // 5: protocol.SearchResponse.results:type_name -> protocol.ResultItem
	1,  // 6: protocol.SearchResponse.error_code:type_name -> protocol.ErrorCode
	0,  // 7: protocol.RegisterRequest.supported_engines:type_name -> protocol.Engine
	4,  // 8: protocol.WorkerStatus.completed_task:type_name -> protocol.SearchResponse
	2,  // 9: protocol.MasterCommand.task:type_name -> protocol.SearchRequest
	5,  // 10: protocol.SearchService.Register:input_type -> protocol.RegisterRequest
	7,  // 11: protocol.SearchService.Connect:input_type -> protocol.WorkerStatus
	6,  // 12: protocol.SearchService.Register:output_type -> protocol.RegisterResponse
	8,  // 13: protocol.SearchService.Connect:output_type -> protocol.MasterCommand
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	file_search_proto_msgTypes[6].OneofWrappers = []any{
		(*MasterCommand_Task)(nil),
		(*MasterCommand_Ping)(nil),
		(*MasterCommand_DisconnectReason)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		EnumInfos:         file_search_proto_enumTypes,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
